-- 15. Rewrite Crossposting Architecture

-- Drop the existing posts table
DROP TABLE IF EXISTS public.posts CASCADE;

-- Recreate posts table with the new JSONB destinations and kanban_status
CREATE TABLE public.posts (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  title TEXT NOT NULL,
  description TEXT,
  notes TEXT,
  kanban_status TEXT DEFAULT 'idea' NOT NULL, -- idea, implementation, test, ready_to_publish, scheduled, published
  
  -- Publish specifics
  is_scheduled BOOLEAN DEFAULT false,
  auto_publish BOOLEAN DEFAULT true,
  scheduled_for TIMESTAMP WITH TIME ZONE,
  
  -- Media Array
  media_urls TEXT[],
  thumbnail_url TEXT,

  -- New: destinations array replacing single platform
  -- Example: [{"platform": "instagram", "status": "scheduled", "post_format": "reel", "external_id": null, "error_log": null}]
  destinations JSONB NOT NULL DEFAULT '[]'::jsonb,
  
  user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE
);

-- Re-enable RLS
ALTER TABLE public.posts ENABLE ROW LEVEL SECURITY;

-- Re-create Policies
CREATE POLICY "Users can view their own posts" ON public.posts FOR SELECT TO authenticated USING (auth.uid() = user_id);
CREATE POLICY "Users can insert their own posts" ON public.posts FOR INSERT TO authenticated WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Users can update their own posts" ON public.posts FOR UPDATE TO authenticated USING (auth.uid() = user_id);
CREATE POLICY "Users can delete their own posts" ON public.posts FOR DELETE TO authenticated USING (auth.uid() = user_id);
