"use client";

import { useState, type ReactNode } from "react";
import { AlertTriangle, Check, ChevronLeft, ChevronRight, ExternalLink, Info, ShieldCheck } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle } from "@/components/ui/dialog";

const permissions = ["instagram_basic", "instagram_content_publish", "instagram_manage_comments", "instagram_manage_messages", "pages_show_list", "pages_read_engagement", "pages_manage_posts", "pages_manage_engagement", "pages_manage_metadata", "publish_video"];

function List({ children }: { children: ReactNode }) { return <ol className="list-decimal space-y-3 pl-5 text-sm leading-6 text-muted-foreground">{children}</ol>; }
function LinkOut({ href, children }: { href: string; children: ReactNode }) { return <a href={href} target="_blank" rel="noreferrer" className="font-medium text-indigo-400 underline underline-offset-4">{children}<ExternalLink className="ml-1 inline size-3" /></a>; }
function Note({ children, warning = false }: { children: ReactNode; warning?: boolean }) { return <div className={`rounded-xl border p-4 text-sm ${warning ? "border-amber-500/25 bg-amber-500/10 text-amber-200" : "border-blue-500/25 bg-blue-500/10 text-blue-200"}`}>{warning ? <AlertTriangle className="mr-2 inline size-4" /> : <Info className="mr-2 inline size-4" />}{children}</div>; }

const steps: Array<{ title: string; description: string; content: ReactNode }> = [
  { title: "Before you begin", description: "Prepare the public app and shared server settings.", content: <div className="space-y-4"><ul className="space-y-2">{["Deploy the latest code to a public HTTPS domain.", "Run Supabase query 18_add_comment_automations.sql.", "Set META_WEBHOOK_VERIFY_TOKEN, META_GRAPH_API_VERSION=v25.0, CRON_SECRET, and SUPABASE_SERVICE_ROLE_KEY.", "Redeploy after changing environment variables."].map(item => <li key={item} className="flex gap-2 text-sm text-muted-foreground"><Check className="mt-0.5 size-4 shrink-0 text-emerald-400" />{item}</li>)}</ul><Note>App ID, App Secret, and access token are user-specific. Save them in Profile, not environment variables.</Note></div> },
  { title: "Open or create the Meta app", description: "Use the Business Portfolio that owns your Page and Instagram account.", content: <List><li>Sign in with the personal Facebook profile that administers the business.</li><li>Open <LinkOut href="https://developers.facebook.com/apps/">Meta for Developers → My Apps</LinkOut>.</li><li>Open your app, or create a Business app connected to the correct portfolio.</li><li>Add Instagram Graph API, Facebook Login for Business, and Webhooks.</li><li>Open <b>App Settings → Basic</b> and privately copy the App ID and App Secret.</li></List> },
  { title: "Create the System User", description: "The System User owns the permanent automation token.", content: <List><li>Open <LinkOut href="https://business.facebook.com/settings">Meta Business Settings</LinkOut> and select the correct portfolio.</li><li>Open <b>Users → System users → Add</b>.</li><li>Create an Employee System User.</li><li>Assign the app with full control.</li><li>Assign the Facebook Page and Instagram account with content-management access.</li></List> },
  { title: "Generate a permanent token", description: "Include publishing, comment, and messaging permissions.", content: <div className="space-y-4"><List><li>Select the System User and click <b>Generate new token</b>.</li><li>Select your app and API version <b>v25.0</b>.</li><li>Select all permissions below and generate the token.</li></List><div className="flex flex-wrap gap-1.5">{permissions.map(item => <code key={item} className="rounded-md bg-muted px-2 py-1 text-[11px] text-indigo-300">{item}</code>)}</div><Note warning><b>Never paste a token into chat, screenshots, documents, or source code.</b> If exposed, revoke it immediately and generate another.</Note></div> },
  { title: "Save the Profile connection", description: "Keep every user’s Meta credentials separate.", content: <div className="space-y-4"><List><li>Return to <b>Profile → Platform Integrations</b>.</li><li>Open Instagram or Facebook.</li><li>Paste the App ID, App Secret, and new System User token.</li><li>Click <b>Save Connection</b>. Instagram and Facebook use the same saved Meta connection.</li></List><Note>These values are stored for the signed-in user in Supabase.</Note></div> },
  { title: "Configure Webhooks", description: "Connect real-time Meta events to your deployed application.", content: <List><li>In Meta App Dashboard, open <b>Webhooks</b> and select <b>Instagram</b>.</li><li>Use callback <code>https://YOUR-DOMAIN.com/api/webhooks/meta</code>.</li><li>Enter the exact deployment value of <code>META_WEBHOOK_VERIFY_TOKEN</code>.</li><li>Keep client certificates off and click <b>Verify and save</b>.</li><li>At v25.0, subscribe to <code>comments</code>, <code>messages</code>, and <code>messaging_postbacks</code>.</li><li>Test each field and send the v25.0 sample to the server.</li></List> },
  { title: "Complete Meta requirements", description: "Real events require a Live app, not Development mode.", content: <List><li>In App Settings → Basic, add your domain without https://.</li><li>Use <code>https://YOUR-DOMAIN.com/privacy</code> for Privacy Policy.</li><li>Use <code>https://YOUR-DOMAIN.com/terms</code> for Terms.</li><li>Use <code>https://YOUR-DOMAIN.com/data-deletion</code> for deletion instructions.</li><li>Add contact email, category, and a 1024 × 1024 icon.</li><li>Complete Required Actions and switch the app to <b>Live</b>.</li></List> },
  { title: "Subscribe the Instagram account", description: "Subscribe the real Professional account, not only the app-level fields.", content: <div className="space-y-4"><List><li>Open <LinkOut href="https://developers.facebook.com/tools/explorer/">Graph API Explorer</LinkOut>, choose your app and v25.0.</li><li>Paste the private System User token into Access Token. Do not generate an Explorer token.</li><li>Run <code>GET /me/accounts?fields=id,name,access_token,instagram_business_account</code>.</li><li>Privately copy the Page access_token and instagram_business_account.id. Never screenshot or share the token.</li><li>Replace Explorer&apos;s token with the returned Page access token.</li><li>Run <code>POST /INSTAGRAM_ACCOUNT_ID/subscribed_apps?subscribed_fields=comments,messages,messaging_postbacks</code>.</li><li>Confirm <code>{`{"success":true}`}</code>.</li></List></div> },
  { title: "Cron and real test", description: "Test the entire journey from comment to resource button.", content: <div className="space-y-4"><List><li>Create a second cronjob.org GET job for <code>https://YOUR-DOMAIN.com/api/cron/process-comment-automations</code> every 5 minutes.</li><li>Add header <code>Authorization: Bearer YOUR_CRON_SECRET</code>.</li><li>Create an automation for one Reel and keyword such as ARM.</li><li>From another Instagram account, comment ARM.</li><li>Confirm the public reply and private message.</li><li>Reply FOLLOWED and confirm the final resource button.</li></List><div className="rounded-xl border border-emerald-500/25 bg-emerald-500/10 p-4 text-sm text-emerald-200"><ShieldCheck className="mr-2 inline size-4" />Setup is complete when account subscription and the real end-to-end test both pass.</div></div> },
];

export function MetaSetupGuide({ open, onOpenChange }: { open: boolean; onOpenChange: (value: boolean) => void }) {
  const [step, setStep] = useState(0);
  const current = steps[step];
  return <Dialog open={open} onOpenChange={onOpenChange}>
    <DialogContent className="flex max-h-[90vh] flex-col overflow-hidden sm:max-w-3xl">
      <DialogHeader><DialogTitle className="flex items-center gap-2"><Info className="size-5 text-blue-400" />Meta setup guide</DialogTitle><DialogDescription>Instagram + Facebook publishing, webhooks, comments, and DMs.</DialogDescription></DialogHeader>
      <div className="flex gap-1.5">{steps.map((item, index) => <button key={item.title} onClick={() => setStep(index)} aria-label={`Go to step ${index + 1}`} className={`h-1.5 flex-1 rounded-full ${index <= step ? "bg-indigo-500" : "bg-muted"}`} />)}</div>
      <div className="min-h-0 flex-1 overflow-y-auto py-4 pr-2"><p className="text-xs font-bold uppercase tracking-widest text-indigo-400">Step {step + 1} of {steps.length}</p><h3 className="mt-2 text-2xl font-bold">{current.title}</h3><p className="mb-6 mt-1 text-sm text-muted-foreground">{current.description}</p><div className="[&_code]:break-all [&_code]:rounded [&_code]:bg-muted [&_code]:px-1.5 [&_code]:py-0.5">{current.content}</div></div>
      <div className="flex justify-between border-t border-border/60 pt-4"><Button variant="ghost" onClick={() => step === 0 ? onOpenChange(false) : setStep(step - 1)}>{step === 0 ? "Close" : <><ChevronLeft className="mr-1 size-4" />Back</>}</Button><Button onClick={() => step === steps.length - 1 ? onOpenChange(false) : setStep(step + 1)} className="bg-indigo-600 text-white hover:bg-indigo-700">{step === steps.length - 1 ? "Finish" : <>Next<ChevronRight className="ml-1 size-4" /></>}</Button></div>
    </DialogContent>
  </Dialog>;
}
